site_name: OpenShift Examples
site_url: https://ocp-examples.github.io
theme:
  name: material
  palette:
    primary: red
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences